### ISSUE TITLE
problem with links on visionontv and loveitorloseit sites

### ISSUE THREAD

**Issue by Openmedianetwork** [tomspost/OMN#5]
Added a #OMN side bar to my parents blog. The project is rolling out, one step at a time. http://www.loveitorloseit.info/

UPDATE: half a step back the links don't work, can we get more testing and feedback on this.

UPDATE: in the Firefox RSS preview window they are not links.

Looking like this might be a miscofig in the RSS creation module?

**Comment by tomspost** [comment]
I am looking into why the links are not work. Can you add a second 3rd RSS
feed so I can see the difference.

**Comment by Openmedianetwork** [comment]
UPDATE: in the Firefox RSS preview window they are not links.

Looking like this might be a miscofig in the RSS creation module?

**Comment by Openmedianetwork** [comment]
added it to feedly the tital headings are a blank link.

**Comment by Openmedianetwork** [comment]
IFTTT say "Feed has items without valid urls" and refuses to add it as a source - was trying to setup auto posting to failbook.
